astra_db:
  collection_name: "ecombot"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "llama3-70b-8192" 